### PR TITLE
Improved scaling on Retina devices.

### PR DESCRIPTION
**Pull request by aroth**
https://github.com/phoboslab/Ejecta/issues/252

### CODE REVIEW

**Comment by collinhover** [comment]
Thanks @aroth, I'll pull this in as soon as I have a bit of time.

**Comment by collinhover** [comment]
@aroth does the window object exist in ejecta's port to iOS? I've been using ig.global as a replacement for window to be safe, but is that necessary?

**Comment by aroth** [comment]
It does as confirmed by this output to the Xcode console:

```
2013-11-17 20:51:10.521 Ejecta[29988:a0b] JS: Does the window object exist in Ejecta's point to iOS?
2013-11-17 20:51:10.522 Ejecta[29988:a0b] JS: [object GlobalObject]
2013-11-17 20:51:10.522 Ejecta[29988:a0b] JS: window.innerWidth: 480
2013-11-17 20:51:10.523 Ejecta[29988:a0b] JS: window.devicePixelRatio: 2
2013-11-17 20:51:10.524 Ejecta[29988:a0b] JS: [object GlobalObject]
2013-11-17 20:51:10.524 Ejecta[29988:a0b] JS: ig.global == window: true

Feel free to use ig.global instead for consistency.
```

**Comment by collinhover** [comment]
Thanks for checking :-)

**Pull request merged**
