### PR TITLE
font.js methods should sanitize text arguments into strings.

### PR DESCRIPTION
**Pull request by arakash92**
yup!

### CODE REVIEW

**Comment by collinhover** [comment]
Thanks for making a pull request! In the future, feel free to do so whenever you think something should be changed.

http://jsperf.com/convert-to-string-bj/3 suggests adding an empty string may be faster. It is also safer, because the current method will error if text is undefined or null. Normally I wouldn't care, but if we're being safe, we might as well be completely safe.

**Comment by arakash92** [comment]
I was thinking about that too. I'm on it.

**Comment by arakash92** [comment]
yep!

**Comment by collinhover** [comment]
Thanks, merged!

**Pull request merged**
