### PR TITLE
F top down

### PR DESCRIPTION
**Pull request by bdaenen**
Added basic top-down support.

### CODE REVIEW

**Comment by collinhover** [comment]
Rad! With 54k additions, you'll have to give me a few days to look through and test things out.

**Comment by bdaenen** [comment]
Most of them are the plus plus files into the example. On second thought I should've probably changed the path to these somehow or created a symlink. I followed the jump run example, but I'll take a look tonight :)

**Comment by collinhover** [comment]
I figured so :-) but you actually bring up a great point. The library itself should be stripped from the examples, because anyone using them already has to copy the impact lib so why not ++ too?

**Comment by bdaenen** [comment]
That actually makes a whole lot of sense :) it's not exactly a complicated process and can easily be put in the readme for new users ^^

I noticed the direction property I put on the Player entity in my example can bug out when the user switches between mouse/touch and keyboard controls, because the lookAt method currently doesn't update it. This doesn't matter too much though, as I assume it'll have to be moved into the Character or Player abstract anyway. At least I think so, because this is the only way I can think of to properly handle offsets for making actions in front of the player (talking to npc's in front of the player, spawning a weapon/projectile in front of the player, ...)

**Comment by collinhover** [comment]
Merged and only two simple conflicts with all the uncommitted changes I've been working on. Testing it now, more soon.

**Comment by collinhover** [comment]
I've been going nuts on fixes and additions. After all of it, I decided to merge your top down example into the jump n run, and let the dev using impact++ just uncomment the TOP_DOWN and FLIP_Y config values if they want to try it in top down mode. I'll add your top down level too and have it loaded instead of the original jump n run level if TOP_DOWN is true.

The direction property is a great idea! I've decided to add a "facing" object to ig.EntityExtended, which is set based on velocity and by the lookAt method. If the game is in top down mode, it will set both x and y facing, otherwise just x facing.

I've got a few more changes to make, namely pathfinding and path following accounting for top down mode. Be careful if you use the latest dev, the changes I've made are fairly big, so check the README changelist.

**Comment by bdaenen** [comment]
That sounds pretty impressive! I was planning to work on fixing touch/mouse based movement of the player in the weekend, as they don't (or didn't, maybe you already fixed them :D) work in my demo.

The facing object is actually an even better idea. I'm guessing it'll also work diagonally, which is quite an improvement.

This weekend, other than the touch/mouse controls I was also planning to look into asynchronous loading of assets. As you probably know Impact loads all assets of the whole game from the start, but I think it should be possible to do this on levelChange by keeping track of which assets are loaded, and which ones are required in the newly loaded level. This would greatly improve the initial wait, and download-time of larger games :)

For this to work we'd need a loading screen in between though, but I'm thinking this could be done with an extra layer, or is there something I'm missing :)?

**Comment by collinhover** [comment]
The facing does handle diagonal, yep, and whatever direction is currently moved in or looked at overrides the other unless both are active.

The deferred level loader is on my list, and I agree it would be a killer feature to have. I'll start an issue request and we can discuss there if you want to take a crack at it.

**Comment by collinhover** [comment]
Also, I think it would be best to keep FLIP_Y, but also add a property to ig.EntityExtended, such as "canFlipY". I'm noticing as I'm making edits for top down that some entities, such as a projectile, can and should be able to flip y whether the game is in top down mode or not, but this is not always the case for characters. Would this work?

edit: along these lines, I'm moving ig.CONFIG.FLIP_Y to ig.CONFIG.ENTITY.CAN_FLIP_Y

**Comment by bdaenen** [comment]
Definitely! It makes sense to make a general config to make all entities flip, but still a way to override this. There will always be situations where you want one entity to flip, but use a unique animation for both up/down (or vice versa) for another. This is a very reasonable feature in my opinion. You could add this property to the EntityExtended class, assign the config.FLIP_Y value to it by default. One would still be able to override it inside the subclasseses where required ^^

**Pull request merged**
